# Generated by Django 4.2.9 on 2026-04-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10),
        ),
    ]
