# Generated by Django 4.2.9 on 2026-05-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_public',
            field=models.BooleanField(default=True),
        ),
    ]
