# Generated by Django 4.2.9 on 2026-03-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('ROOM', 'Habitación'), ('FULL', 'Piso entero'), ('STUDIO', 'Estudio')], default='ROOM', max_length=10)),
                ('price_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('room_m2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_m2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('companions', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('elevator', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('gender_pref', models.CharField(choices=[('NONE', 'Sin preferencia'), ('FEMALE', 'Solo chicas'), ('MALE', 'Solo chicos')], default='NONE', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_walk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minutes_transit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.university')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('WIFI', 'WiFi alta velocidad'), ('UTILITIES', 'Gastos incluidos'), ('FURNISHED', 'Amueblado'), ('PARKING', 'Parking'), ('AC', 'Aire acondicionado'), ('HEATING', 'Calefacción'), ('WASHER', 'Lavadora'), ('DESK', 'Escritorio estudio'), ('ERGONOMIC_CHAIR', 'Silla ergonómica'), ('ELEVATOR', 'Ascensor')], max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property')),
            ],
        ),
    ]
