# Generated by Django 4.2.9 on 2026-03-24 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='universities',
            field=models.ManyToManyField(blank=True, through='properties.PropertyUniversity', to='properties.university'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='propertyuniversity',
            unique_together={('property', 'university')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenity',
            unique_together={('property', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'property')},
        ),
    ]
